# Generated by Django 4.1.2 on 2022-11-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название страницы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Ссылка'),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('upload', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.pages')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
