# Generated by Django 4.1.2 on 2022-12-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_status_options_remove_status_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.TextField(db_index=True, max_length=100, verbose_name='Способ получения')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Способ получения',
                'verbose_name_plural': 'Способ получения',
                'ordering': ('delivery',),
            },
        ),
        migrations.AlterField(
            model_name='status',
            name='orderstatus',
            field=models.TextField(db_index=True, max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.delivery', verbose_name='Способ получения'),
            preserve_default=False,
        ),
    ]
