# Generated by Django 4.1.2 on 2022-12-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delivery_alter_status_orderstatus_orders_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('status',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='number',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery',
            field=models.TextField(db_index=True, max_length=50, verbose_name='Способ получения'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='adress',
            field=models.TextField(blank=True, max_length=150, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.TextField(blank=True, max_length=50, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.TextField(blank=True, max_length=100, verbose_name='Всего товаров'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.TextField(blank=True, max_length=50, verbose_name='К оплате'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.TextField(blank=True, max_length=200, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TextField(blank=True, max_length=20, verbose_name='Время доставки'),
        ),
    ]
