# Generated by Django 4.1.2 on 2022-12-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_orders_options_alter_orders_index_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, max_length=150, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(blank=True, max_length=50, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TimeField(blank=True, max_length=20, verbose_name='Время доставки'),
        ),
    ]
