# Generated by Django 4.1.2 on 2022-12-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_orders_items_remove_orders_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.TextField(blank=True, max_length=150, verbose_name='Способ получения'),
        ),
    ]
